/* eslint-disable */
/**
 * Generated utilities for implementing server-side Convex query and mutation functions.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.9.1.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import {
  ActionBuilderForAPI,
  HttpEndpointBuilderForAPI,
  MutationBuilder,
  QueryBuilderForDataModel,
  ActionCtx as GenericActionCtx,
  HttpEndpointCtx as GenericHttpEndpointCtx,
  MutationCtx as GenericMutationCtx,
  QueryCtx as GenericQueryCtx,
  DatabaseReader as GenericDatabaseReader,
  DatabaseWriter as GenericDatabaseWriter,
} from "convex/server";
import type { DataModel } from "./dataModel.js";
import type { API } fr